/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class reply_jnitest_NativeConnector */

#ifndef _Included_reply_jnitest_NativeConnector
#define _Included_reply_jnitest_NativeConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     reply_jnitest_NativeConnector
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_reply_jnitest_NativeConnector_getText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
